-- First, remove the table if it exists
drop table if exist items;

-- Create the table anew
create table items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url TEXT NOT NULL, 
    title TEXT NOT NULL, 
    rating INTEGER NOT NULL, 
    description TEXT  
);

-- insert some test data
-- Using a multi-row insert statement here


-- TO EXECUTE FILE TO THIS 
-- inventory=> \i ~/path/to/file/customers.sql 
-- psql:~/path/to/file/customers.sql:2: NOTICE:  table "customers" does not exist, skipping
-- DROP TABLE
-- CREATE TABLE
-- INSERT 0 3
-- inventory=>